#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_SUPERUSER" <<-EOSQL
    CREATE USER $POSTGRES_USER WITH PASSWORD '$POSTGRES_PASSWORD';
    CREATE DATABASE $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $POSTGRES_USER;
    ALTER DATABASE $POSTGRES_USER CHARACTER SET utf8 COLLATE utf8_general_ci;
EOSQL
