# Generated by Django 2.0.7 on 2018-07-11 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('account_id', models.IntegerField(primary_key=True, serialize=False)),
                ('personname', models.CharField(db_index=True, max_length=256)),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerHero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_id', models.IntegerField()),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heroes', to='dota2app.Player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.IntegerField()),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='dota2app.Player')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='playermatch',
            unique_together={('account', 'match_id')},
        ),
        migrations.AlterIndexTogether(
            name='playermatch',
            index_together={('account', 'match_id')},
        ),
        migrations.AlterUniqueTogether(
            name='playerhero',
            unique_together={('account', 'hero_id')},
        ),
        migrations.AlterIndexTogether(
            name='playerhero',
            index_together={('account', 'hero_id')},
        ),
    ]
